### PR TITLE
Add moz prefix vendors and a mixin to background clip

### PR DESCRIPTION
**Pull request by bicho44**
I Added moz prefix vendors and a mixin to background clip.
I hope you like it.

### CODE REVIEW

**Comment by bicho44** [comment]
I added a auto Color Scheme

**Comment by mdo** [comment]
Dig the addition of the background clip, but unsure of the color scheme. How would I use such a thing—have an example in mind?

**Comment by bicho44** [comment]
Hi:
You can see a [Demo Color Scheme](http://imgdigital.com.ar/colorscheme/) i make for you. I hope its clear enough.
If you need more info, ask :D

**Comment by divyekapoor** [comment]
I dig the colour scheme. :) 
+1 for inclusion, please. :)

(I hate being stuck choosing colours while the designer's finalizing the colour scheme with the client).
Plus a single colour based colour scheme is good for prototyping! :)

**Comment by bicho44** [comment]
Thanks, i like you like it

**Comment by mdo** [comment]
Punting this and all other issues against master ahead of v2 release.

Nuked background clip entirely in v2. Never use it and I haven't heard many others using it either. Can always add it back though. Thanks!

**Pull request closed without merging**
