### PR TITLE
Additions to bootstrap.less

### PR DESCRIPTION
**Pull request by johanbrook**
Added some handy mixins from my personal library:
- **Clearfix.** For easy clearing of floats directly from the Less code. No need for .clearfix classes in HTML.
- **Columns.** CSS3 Columns. Pretty straight-forward.
- **Hover.** For use with simple background sprites. Include the mixin whenever there's need for the background image to shift to the bottom.
- **Button.** This is ideal for CSS preprocessors.

### CODE REVIEW

**Comment by mdo** [comment]
Clearfix, columns, and buttons seem useful and should be added, but I'm unsure why hover would need to be a mixin. It's use case seems fairly limited.

**Comment by johanbrook** [comment]
This clearfix method is explained [here](http://perishablepress.com/press/2009/12/06/new-clearfix-hack/) and [here](http://stackoverflow.com/questions/211383/which-method-of-clearfix-is-best), and was originally conceived [here](http://www.positioniseverything.net/easyclearing.html).

You can go with the simpler one, of course. It's nevertheless nice to have the ability to clear floats directly from the CSS with a mixin (in case you would like to change the method later on).

**Comment by mdo** [comment]
Got it. I've added nearly mixins for all these things. I would have merged your fork and edited them, but I'm still figuring out Github's more advanced features and am unsure how to merge all this stuff :).

Thanks for doing these—didn't think to do .clearfix or the CSS3 columns at all.

**Comment by johanbrook** [comment]
Awesome, great to see them in there.

To merge pull requests next time, simple consult the "Merge Help" button in the upper right corner of this comment box. That'll show all relevant terminal commands. Looks like this for me (another pull request for my repo):

Pull request

Simply:
1. `git checkout` creates and switches to a new branch. Always do this to separate your code from the committer's.
2. `git pull` brings down my changes from my repo into your newly created branch.
3. `git merge` merges (duh) your and the committer's changes.

**Pull request closed without merging**
